In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('real_estate.csv')

In [3]:
df

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
0,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,home,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
1,14400000.0,Under Construction,1528,"9,450",3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Property In Gurgaon,Approved by RERA,3.0,M3M Antalya Hills Phase I,M3M,Apartment
2,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
3,40000000.0,Ready to move,4500,"8,888",4 BHK Independent Floor,Sector 57,MM India Pvt Ltd,Not approved by RERA,4.0,Outside Socity,Outside,Plot
4,24000000.0,Under Construction,1800,"13,333",3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,MM India Pvt Ltd,Approved by RERA,3.0,Anant Raj Estate Plots,Anant,Floor
...,...,...,...,...,...,...,...,...,...,...,...,...
19510,24100000.0,Ready to move,1381,"17,500",2 BHK Apartment in Sobha City,Sector 108,Shree Realstic One,Not approved by RERA,2.0,Sobha City,Sobha,Apartment
19511,36200000.0,Ready to move,2072,"17,500",3 BHK Apartment in Sobha City,Sector 108,Shree Realstic One,Not approved by RERA,3.0,Sobha City,Sobha,Apartment
19512,39100000.0,Under Construction,2445,"16,002",3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment
19513,37700000.0,Under Construction,2360,"16,001",3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment
19514,36500000.0,Under Construction,2282,"16,005",3 BHK Apartment in Pyramid Alban,Sector 71,Shree Realstic One,Approved by RERA,3.0,Pyramid Alban,Pyramid,Apartment

In [4]:
df.head()

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
0,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,home,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
1,14400000.0,Under Construction,1528,"9,450",3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Property In Gurgaon,Approved by RERA,3.0,M3M Antalya Hills Phase I,M3M,Apartment
2,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
3,40000000.0,Ready to move,4500,"8,888",4 BHK Independent Floor,Sector 57,MM India Pvt Ltd,Not approved by RERA,4.0,Outside Socity,Outside,Plot
4,24000000.0,Under Construction,1800,"13,333",3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,MM India Pvt Ltd,Approved by RERA,3.0,Anant Raj Estate Plots,Anant,Floor

In [5]:
df.columns

Index(['Price', 'Status', 'Area', 'Rate per sqft', 'Property Type', 'Locality',
       'Builder Name', 'RERA Approval', 'BHK_Count', 'Socity', 'Company Name',
       'Flat Type'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19515 entries, 0 to 19514
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          19515 non-null  str
 1   Status         19515 non-null  str
 2   Area           19515 non-null  int64
 3   Rate per sqft  19515 non-null  str
 4   Property Type  19515 non-null  str
 5   Locality       19515 non-null  str
 6   Builder Name   19515 non-null  str
 7   RERA Approval  19515 non-null  str
 8   BHK_Count      19515 non-null  float64
 9   Socity         19515 non-null  str
 10  Company Name   19515 non-null  str
 11  Flat Type      19515 non-null  str
dtypes: float64(1), int64(1), str(10)
memory usage: 4.5 MB

In [7]:
df.describe()

                Area     BHK_Count
count   19515.000000  19515.000000
mean     2545.455752      3.229772
std      9550.629288      4.923873
min        60.000000      0.000000
25%      1423.000000      3.000000
50%      2000.000000      3.000000
75%      2800.000000      4.000000
max    958320.000000    132.000000

In [8]:
df.isnull().sum()

Price            0
Status           0
Area             0
Rate per sqft    0
Property Type    0
Locality         0
Builder Name     0
RERA Approval    0
BHK_Count        0
Socity           0
Company Name     0
Flat Type        0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(5292)

In [10]:
df.shape

(19515, 12)

In [11]:
df[df.duplicated(keep=False)]

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
0,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,home,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
1,14400000.0,Under Construction,1528,"9,450",3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Property In Gurgaon,Approved by RERA,3.0,M3M Antalya Hills Phase I,M3M,Apartment
2,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
3,40000000.0,Ready to move,4500,"8,888",4 BHK Independent Floor,Sector 57,MM India Pvt Ltd,Not approved by RERA,4.0,Outside Socity,Outside,Plot
4,24000000.0,Under Construction,1800,"13,333",3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,MM India Pvt Ltd,Approved by RERA,3.0,Anant Raj Estate Plots,Anant,Floor
...,...,...,...,...,...,...,...,...,...,...,...,...
19454,9500000.0,Resale,1080,"8,796",Residential Plot in Vatika Express City Plots,Sector 88A,seller,Approved by RERA,0.0,Vatika Express City Plots,Vatika,Plot
19468,9500000.0,Resale,1188,"7,996",Residential Plot in Vatika Express City Plots,Sector 88A,seller,Approved by RERA,0.0,Vatika Express City Plots,Vatika,Plot
19469,9500000.0,Resale,1188,"7,996",Residential Plot in Vatika Express City Plots,Sector 88A,seller,Approved by RERA,0.0,Vatika Express City Plots,Vatika,Plot
19496,34700000.0,Under Construction,2107,"16,500",3 BHK Apartment in Elan The Presidential,Sector 106,Property In Gurgaon,Approved by RERA,3.0,Elan The Presidential,Elan,Apartment
19497,51100000.0,Under Construction,3100,"16,500",4 BHK Apartment in Elan The Presidential,Sector 106,properties for sale in Gurgaon,Approved by RERA,4.0,Elan The Presidential,Elan,Apartment

In [12]:
df.columns=df.columns.str.strip().str.lower().str.replace(' ', '_')

In [13]:
df.rename(columns={'socity' : 'society'}, inplace=True)

In [14]:
df.columns

Index(['price', 'status', 'area', 'rate_per_sqft', 'property_type', 'locality',
       'builder_name', 'rera_approval', 'bhk_count', 'society', 'company_name',
       'flat_type'],
      dtype='str')

In [15]:
df['price'].unique()[:20]

<ArrowStringArray>
[        '10700000.0',         '14400000.0',         '40000000.0',
         '24000000.0',         '63800000.0',          '4500000.0',
          '9000000.0',         '74900000.0',         '19700000.0',
         '80100000.0', '13700000.000000002',         '22000000.0',
         '15000000.0',         '44000000.0',         '12000000.0',
         '52500000.0',          '4600000.0',         '30000000.0',
          '9900000.0',         '45300000.0']
Length: 20, dtype: str

In [16]:
df['price']=df['price'].apply(lambda x:x.strip())

In [17]:
df['price'] = df['price'].str.strip().str.replace(',', '').astype(float)

In [18]:
df['rate_per_sqft']=df['rate_per_sqft'].apply(lambda x:x.strip())

In [19]:
df['rate_per_sqft'] = df['rate_per_sqft'].str.strip().str.replace(',', '').astype(float)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19515 entries, 0 to 19514
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          19515 non-null  float64
 1   status         19515 non-null  str
 2   area           19515 non-null  int64
 3   rate_per_sqft  19515 non-null  float64
 4   property_type  19515 non-null  str
 5   locality       19515 non-null  str
 6   builder_name   19515 non-null  str
 7   rera_approval  19515 non-null  str
 8   bhk_count      19515 non-null  float64
 9   society        19515 non-null  str
 10  company_name   19515 non-null  str
 11  flat_type      19515 non-null  str
dtypes: float64(3), int64(1), str(8)
memory usage: 4.2 MB

In [21]:
df.duplicated().sum()

np.int64(5292)

In [22]:
df=df.drop_duplicates()

In [23]:
df['status']=df['status'].str.lower().str.strip()

In [24]:
df['rera_approval']=df['rera_approval'].str.lower().str.strip().map({'not approved by rera':False, 'approved by rera':True})

In [25]:
categorical_cols = df.select_dtypes(include="string").columns

df[categorical_cols] = df[categorical_cols].apply(
    lambda col: col.str.lower().str.strip()
)

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 14223 entries, 0 to 19514
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          14223 non-null  float64
 1   status         14223 non-null  str
 2   area           14223 non-null  int64
 3   rate_per_sqft  14223 non-null  float64
 4   property_type  14223 non-null  str
 5   locality       14223 non-null  str
 6   builder_name   14223 non-null  str
 7   rera_approval  14223 non-null  bool
 8   bhk_count      14223 non-null  float64
 9   society        14223 non-null  str
 10  company_name   14223 non-null  str
 11  flat_type      14223 non-null  str
dtypes: bool(1), float64(3), int64(1), str(7)
memory usage: 2.8 MB